/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    projects: Project;
    caseStudies: CaseStudy;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    caseStudies: CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  slug: string;
  title: string;
  leadText: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  content?:
    | (
        | {
            fullWidthImage: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'fullWidthImage';
          }
        | {
            heading?: string | null;
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            colSpan?: ('12' | '11' | '10' | '9' | '8' | '7' | '6' | '5' | '4' | '3') | null;
            colStart?: ('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
            singleMedia: number | Media;
            aspectRatio?:
              | ('auto' | 'aspect-square' | 'aspect-video' | 'aspect-[3/4]' | 'aspect-[9/16]' | 'aspect-[21/9]')
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'singleMedia';
          }
        | {
            text?: string | null;
            buttonText?: string | null;
            destination?:
              | ({
                  relationTo: 'projects';
                  value: number | Project;
                } | null)
              | ({
                  relationTo: 'caseStudies';
                  value: number | CaseStudy;
                } | null);
            /**
             * Leave empty to use the destination link
             */
            customUrl?: string | null;
            variant?: ('1' | '2') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'CallToAction';
          }
        | {
            backgroundColor?: ('#252525' | '#e4e4e4' | 'whitesmoke') | null;
            content?:
              | (
                  | {
                      heading?: string | null;
                      text?: {
                        root: {
                          type: string;
                          children: {
                            type: any;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          version: number;
                        };
                        [k: string]: unknown;
                      } | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'textBlock';
                    }
                  | {
                      colSpan?: ('12' | '11' | '10' | '9' | '8' | '7' | '6' | '5' | '4' | '3') | null;
                      colStart?:
                        | ('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12')
                        | null;
                      singleMedia: number | Media;
                      aspectRatio?:
                        | (
                            | 'auto'
                            | 'aspect-square'
                            | 'aspect-video'
                            | 'aspect-[3/4]'
                            | 'aspect-[9/16]'
                            | 'aspect-[21/9]'
                          )
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'singleMedia';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'recursiveComponent';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseStudies".
 */
export interface CaseStudy {
  id: number;
  slug: string;
  title: string;
  leadText: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  content?:
    | (
        | {
            fullWidthImage: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'fullWidthImage';
          }
        | {
            heading?: string | null;
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            colSpan?: ('12' | '11' | '10' | '9' | '8' | '7' | '6' | '5' | '4' | '3') | null;
            colStart?: ('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12') | null;
            singleMedia: number | Media;
            aspectRatio?:
              | ('auto' | 'aspect-square' | 'aspect-video' | 'aspect-[3/4]' | 'aspect-[9/16]' | 'aspect-[21/9]')
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'singleMedia';
          }
        | {
            text?: string | null;
            buttonText?: string | null;
            destination?:
              | ({
                  relationTo: 'projects';
                  value: number | Project;
                } | null)
              | ({
                  relationTo: 'caseStudies';
                  value: number | CaseStudy;
                } | null);
            /**
             * Leave empty to use the destination link
             */
            customUrl?: string | null;
            variant?: ('1' | '2') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'CallToAction';
          }
        | {
            backgroundColor?: ('#252525' | '#e4e4e4' | 'whitesmoke') | null;
            content?:
              | (
                  | {
                      heading?: string | null;
                      text?: {
                        root: {
                          type: string;
                          children: {
                            type: any;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          version: number;
                        };
                        [k: string]: unknown;
                      } | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'textBlock';
                    }
                  | {
                      colSpan?: ('12' | '11' | '10' | '9' | '8' | '7' | '6' | '5' | '4' | '3') | null;
                      colStart?:
                        | ('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12')
                        | null;
                      singleMedia: number | Media;
                      aspectRatio?:
                        | (
                            | 'auto'
                            | 'aspect-square'
                            | 'aspect-video'
                            | 'aspect-[3/4]'
                            | 'aspect-[9/16]'
                            | 'aspect-[21/9]'
                          )
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'singleMedia';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'recursiveComponent';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'caseStudies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  leadText?: T;
  content?:
    | T
    | {
        fullWidthImage?:
          | T
          | {
              fullWidthImage?: T;
              id?: T;
              blockName?: T;
            };
        textBlock?:
          | T
          | {
              heading?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        singleMedia?:
          | T
          | {
              colSpan?: T;
              colStart?: T;
              singleMedia?: T;
              aspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        CallToAction?:
          | T
          | {
              text?: T;
              buttonText?: T;
              destination?: T;
              customUrl?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        recursiveComponent?:
          | T
          | {
              backgroundColor?: T;
              content?:
                | T
                | {
                    textBlock?:
                      | T
                      | {
                          heading?: T;
                          text?: T;
                          id?: T;
                          blockName?: T;
                        };
                    singleMedia?:
                      | T
                      | {
                          colSpan?: T;
                          colStart?: T;
                          singleMedia?: T;
                          aspectRatio?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseStudies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  leadText?: T;
  content?:
    | T
    | {
        fullWidthImage?:
          | T
          | {
              fullWidthImage?: T;
              id?: T;
              blockName?: T;
            };
        textBlock?:
          | T
          | {
              heading?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        singleMedia?:
          | T
          | {
              colSpan?: T;
              colStart?: T;
              singleMedia?: T;
              aspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        CallToAction?:
          | T
          | {
              text?: T;
              buttonText?: T;
              destination?: T;
              customUrl?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        recursiveComponent?:
          | T
          | {
              backgroundColor?: T;
              content?:
                | T
                | {
                    textBlock?:
                      | T
                      | {
                          heading?: T;
                          text?: T;
                          id?: T;
                          blockName?: T;
                        };
                    singleMedia?:
                      | T
                      | {
                          colSpan?: T;
                          colStart?: T;
                          singleMedia?: T;
                          aspectRatio?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}